<?php


namespace App\Transformers\Errand;


use App\Models\Errand;

class FullErrandTransformer extends BaseErrandTransformer
{
    public function transform(Errand $errand)
    {
        $data = parent::transform($errand); // TODO: Change the autogenerated stub
        $data['hidden_content'] = $errand->hidden_content;
        $data['payment_out_trade_no'] = $errand->payment_out_trade_no;
        return $data;
    }
}